version: "3.7"

services:
  db:
    container_name: ganga_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: Ganga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dinesh123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ganga_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network

  pgadmin:
    container_name: ganga_pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ganga.net.in
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "8080:80"
    volumes:
      - ganga_pgadmin:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    tty: true
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  ganga_pgadmin:
  ganga_postgres:
